<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-08-08 22:57:12
 * @@Modify Date: 2016-08-04 22:14:43
 * @@Function:
 */
 ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('alothemes/labels');
    $catId = $this->getActive();
    if(is_null($catId)) $catId = $this->getRequest()->getParam('type');
?>

<div class="mage-magictabs mc-<?php echo $catId;?>">
    <?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php 
        $config = $this->getWidgetCfg(); 
        $width  = $config['widthImages'];
        $height  = $config['heightImages'];
        $actions = isset($config['action']) ? $config['action'] : array();
    ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_rowCount = isset($config['row']) ? $config['row'] : 1; //$this->getColumnCount(); ?>
    <?php $j=0; $time = isset($config['productDelay']) ? $config['productDelay'] : 0; ?>
    <div class="flexisel-content products-grid <?php echo $catId;?> zoomOut play">
    <?php $i=1; foreach ($_productCollection as $_product): ?>
			<?php if($i%5==1) echo '<div class="product product-items">'; ?>
			<?php if($i%5==1 || $i%5==4 || $i%5 == 3) echo '<div class="sub-item item product-item">'; ?>
            <?php $t = $j*$time; $t .='ms'; $j++; ?>

                <div style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="items item-animate">
                    <div class="per-product">
                        <div class="link-view pull-left-none"> 
							<a title="<?php echo $this->__('Quick View') ?>" href="<?php echo $this->getUrl('magicshop/quickview/view') .'id/'.$_product->getId()?>" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i><?php //echo $this->__('Quick View') ?>
							</a>
						</div>
                        <div class="images-container">
						    
							<h2 class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
							</h2>
						    <div class="product-hover">
							    <?php echo $helpLabels->getLabels($_product); //Product labels ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								
								   <?php $imagehv = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position','2');
									if($imagehv): $imagehv = $imagehv->getFile();
									?>
										<span class="product-img-back">
											<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $imagehv)->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</span>
									<?php endif ?>
								</a>
							</div> 
							<?php if($actions):?>
							<div class="actions-no hover-box">
								<div class="actions">
									<?php echo $this->getPriceHtml($_product, true) ?>
										<?php if(in_array("cart", $actions)):?>
											<?php if($_product->isSaleable()): ?>
												<div class="actions-cart">
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span>
													</button>
												</div>
											<?php else: ?>
												<p class="availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"><span><?php echo $this->__('Out of stock') ?></span></p>
											<?php endif; ?>
										<?php endif; ?>
										<ul class="add-to-links">
											<?php if(in_array("compare", $actions)):?>
												<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
													<li class="pull-right-no pull-compare"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Compare') ?>" class="link-compare"><i class="icon icon-compare"></i><?php echo $this->__('Compare') ?></a></li>
												<?php endif; ?>
											<?php endif; ?>
											
											<?php if(in_array("wishlist", $actions)):?>
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
													<li class="pull-left-no pull-wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Wishlist') ?>" class="link-wishlist"><i class="icon icon-favorites"></i><?php echo $this->__('Wishlist') ?></a></li>
												<?php endif; ?>
											<?php endif; ?>
										</ul>
								</div>
							</div>
							<?php endif ?>
                        </div>
						<?php if(in_array("review", $actions)):?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php endif ?>
    				</div>
                </div>
			<?php if($i%5==0 || $i%5==2 || $i%5 == 3 || $i==$_collectionSize) echo '</div>'; ?>
			<?php if($i%5==0 || $i==$_collectionSize) echo '</div>'; $i++;?>
        <?php endforeach ?>
    </div>
<?php endif; ?>
</div>


